#!/usr/bin/env python3
from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


FRONTMATTER_RE = re.compile(r"\A---\s*\n(.*?)\n---\s*\n", re.DOTALL)


@dataclass(frozen=True)
class Article:
    path: Path
    title: str
    author: str
    published: str
    captured: str
    source_url: str

    @property
    def year(self) -> str:
        for v in (self.published, self.captured):
            if v and len(v) >= 4:
                return v[:4]
        return "unknown"


def parse_frontmatter(text: str) -> dict[str, str]:
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}
    block = m.group(1)
    data: dict[str, str] = {}
    for raw in block.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        key = key.strip()
        value = value.strip()
        if "#" in value:
            value = value.split("#", 1)[0].strip()
        if value.startswith('"') and value.endswith('"') and len(value) >= 2:
            value = value[1:-1]
        data[key] = value
    return data


def iter_articles(repo_root: Path) -> Iterable[Article]:
    for path in sorted((repo_root / "articles").rglob("*.md")):
        text = path.read_text(encoding="utf-8")
        fm = parse_frontmatter(text)
        title = fm.get("title", "").strip()
        source_url = fm.get("source_url", "").strip()
        if not title or not source_url:
            continue
        yield Article(
            path=path,
            title=title,
            author=fm.get("author", "").strip(),
            published=fm.get("published", "").strip(),
            captured=fm.get("captured", "").strip(),
            source_url=source_url,
        )


def main() -> int:
    repo_root = Path(__file__).resolve().parents[1]
    articles = list(iter_articles(repo_root))

    lines: list[str] = []
    lines.append("# Article Index")
    lines.append("")
    lines.append("This file is generated by `python3 scripts/build_index.py`.")
    lines.append("")

    by_year: dict[str, list[Article]] = {}
    for a in articles:
        by_year.setdefault(a.year, []).append(a)

    for year in sorted(by_year.keys(), reverse=True):
        lines.append(f"## {year}")
        lines.append("")
        for a in by_year[year]:
            rel_path = a.path.relative_to(repo_root).as_posix()
            date_label = a.published or a.captured or year
            author_suffix = f" — {a.author}" if a.author else ""
            lines.append(f'- {date_label} - [{a.title}]({rel_path}){author_suffix}')
        lines.append("")

    (repo_root / "INDEX.md").write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(repo_root / "INDEX.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
